backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey" # Replace with your Uploadcare public key
    multiple: false
    tabs: "file camera url facebook gdrive gphotos"
    effects: "crop,rotate,enhance,sharp,grayscale"
    imageShrink: "1024x1024"
    previewStep: true
    clearable: true
collections:
  - name: "costa-rica"
    label: "Costa Rica Gallery"
    folder: "content/gallery/costa-rica"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          config: {
            multiple: false
          }
        }
  - name: "colombia"
    label: "Colombia Gallery"
    folder: "content/gallery/colombia"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          config: {
            multiple: false
          }
        }
  - name: "canada"
    label: "Canada Gallery"
    folder: "content/gallery/canada"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          config: {
            multiple: false
          }
        }
  - name: "netherlands"
    label: "Netherlands Gallery"
    folder: "content/gallery/netherlands"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          config: {
            multiple: false
          }
        }