backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "costa-rica"
    label: "Costa Rica Gallery"
    folder: "content/gallery/costa-rica"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "hidden", default: "costa-rica" }
      - label: "Images"
        name: "images"
        widget: "image"
        media_library:
          config:
            multiple: true

  - name: "colombia"
    label: "Colombia Gallery"
    folder: "content/gallery/colombia"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "hidden", default: "colombia" }
      - label: "Images"
        name: "images"
        widget: "image"
        media_library:
          config:
            multiple: true

  - name: "canada"
    label: "Canada Gallery"
    folder: "content/gallery/canada"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "hidden", default: "canada" }
      - label: "Images"
        name: "images"
        widget: "image"
        media_library:
          config:
            multiple: true

  - name: "netherlands"
    label: "Netherlands Gallery"
    folder: "content/gallery/netherlands"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "hidden", default: "netherlands" }
      - label: "Images"
        name: "images"
        widget: "image"
        media_library:
          config:
            multiple: true